version: '3.3'
services:
  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password --port 4306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'root'
    ports:
      - '4306:4306'
  web:
    build: .
    volumes:
      - .:/echaequipos-backend:cached
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_HOST: 'db'
      DATABASE_PORT: '4306'
volumes:
  db:
